### ISSUE TITLE
CommonsBeanutilsCollectionsLogging1 throws InvocationTargetException on deserialization

### ISSUE THREAD

**Issue by jasinner** [frohoff/ysoserial#27] opened 2016-03-11 07:31 UTC
I'm trying out CommonsBeanutilsCollectionsLogging1 and while it does pass the Unit Test, it doesn't seem to actually lead to RuntimeExec execution during deserialization. Instead a get an exception from BeanComparator:

Haven't had a chance to add more debugging to BeanComparator yet, but did anyone else get this to work?

`Exception in thread "main" java.lang.RuntimeException: InvocationTargetException: java.lang.reflect.InvocationTargetException
	at org.apache.commons.beanutils.BeanComparator.compare(BeanComparator.java:171)
	at java.util.PriorityQueue.siftDownUsingComparator(PriorityQueue.java:721)
	at java.util.PriorityQueue.siftDown(PriorityQueue.java:687)
	at java.util.PriorityQueue.heapify(PriorityQueue.java:736)
	at java.util.PriorityQueue.readObject(PriorityQueue.java:795)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1058)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1900)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371)
	at testSerialization.Deserializer.main(Deserializer.java:14)
`

**Comment by frohoff** [comment] 2016-03-11 07:54
On OSX with JDK 1.8.0_73 I can see it hit a breakpoint in my IDE at `Runtime.exec()` and then it pops Calculator, __after which__ it throws the same error as above (root cause `NullPointerException` at `AbstractTranslet.postInitialization()` on line 372.

Definitely could use some more solid ways of testing this stuff.

**Comment by frohoff** [comment] 2016-03-22 14:11
@jasinner can you confirm whether this is working for you or no so we can resolve?

**Comment by jasinner** [comment] 2016-03-23 07:00
Yes Chris,
This payload worked for me when using the updated test harness on MacOSX.
I'll try and find time to update the test harness for Windows. I think it's
just a matter of changing the class to runtime.exec to take a String array.

**Comment by frohoff** [comment] 2016-03-23 15:06
Thanks. Closing this for now then.

**Closed by frohoff** 2016-03-23 15:06 UTC
