### ISSUE TITLE
CommonsCollections1 Can not running

### ISSUE THREAD

**Issue by evilmiracle** [frohoff/ysoserial#79] opened 2018-01-26 13:28 UTC
My environment is

windows 10 pro

java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

so when i run the ysoserial commonsCollections1 by IDEA 2017

i see the error code in my monitor

the code is 

`generating payload object(s) for command: 'calc.exe'
serializing payload
deserializing payload
java.lang.annotation.IncompleteAnnotationException: java.lang.Override missing element entrySet
	at sun.reflect.annotation.AnnotationInvocationHandler.invoke(AnnotationInvocationHandler.java:81)
	at com.sun.proxy.$Proxy0.entrySet(Unknown Source)
	at sun.reflect.annotation.AnnotationInvocationHandler.readObject(AnnotationInvocationHandler.java:452)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1058)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2136)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2027)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1535)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:422)
	at ysoserial.Deserializer.deserialize(Deserializer.java:27)
	at ysoserial.Deserializer.deserialize(Deserializer.java:22)
	at ysoserial.payloads.util.PayloadRunner.run(PayloadRunner.java:39)
	at ysoserial.payloads.CommonsCollections1.main(CommonsCollections1.java:84)`

and the CommonsCollections3 same to CommonsCollections1 as.

Thank you!

**Comment by evilmiracle** [comment] 2018-01-26 13:29
how can fixed this？

**Comment by frohoff** [comment] 2018-02-08 23:22
This is a duplicate of #17 and #65. Closing.

**Closed by frohoff** 2018-02-08 23:22 UTC
Labels: duplicate
