### ISSUE TITLE
java.lang.annotation.IncompleteAnnotationException: java.lang.Override missing element entrySet

### ISSUE THREAD

**Issue by xiaomingdaily** [frohoff/ysoserial#65] opened 2017-03-25 14:37 UTC
i download the source from github,but i cannot test "CommonsCollections3" and pop up error below, how to solve this error,thank you.
---
   my env is windows ,java version "1.8.0_121"。
---

java.lang.annotation.IncompleteAnnotationException: java.lang.Override missing element entrySet
	at sun.reflect.annotation.AnnotationInvocationHandler.invoke(AnnotationInvocationHandler.java:81)
	at com.sun.proxy.$Proxy0.entrySet(Unknown Source)
	at sun.reflect.annotation.AnnotationInvocationHandler.readObject(AnnotationInvocationHandler.java:452)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1058)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1909)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1808)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:373)
	at ysoserial.Deserializer.deserialize(Deserializer.java:27)
	at ysoserial.Deserializer.deserialize(Deserializer.java:22)
	at ysoserial.payloads.util.PayloadRunner.run(PayloadRunner.java:37)
	at ysoserial.payloads.CommonsCollections3.main(CommonsCollections3.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)

**Comment by 0xwindows** [comment] 2017-03-25 17:58
java version "1.8.0_65"

Caused by: java.io.IOException: Cannot run program "calc.exe": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at java.lang.Runtime.exec(Runtime.java:450)
	at java.lang.Runtime.exec(Runtime.java:347)
	at ysoserial.Pwner44530500755210.<clinit>(Gadgets.java)
	... 36 more
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:248)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 40 more

**Comment by frohoff** [comment] 2017-09-02 21:10
The `java.lang.annotation.IncompleteAnnotationException: java.lang.Override missing element entrySet
` error is caused by hardening in JDK classes and is expected behavior. See http://www.thegreycorner.com/2016/05/commoncollections-deserialization.html. Closing.

**Closed by frohoff** 2017-09-02 21:10 UTC
