### ISSUE TITLE
Printing weird output as payload in Windows_64x

### ISSUE THREAD

**Issue by ProgramFilesx86** [frohoff/ysoserial#161] opened 2021-06-29 17:45 UTC
See the video

https://user-images.githubusercontent.com/35371691/123843440-31054600-d912-11eb-839d-684528081b2e.mp4

the payload seems very strange and doesn't work out either (as it was different than the other payloads from other OS)
What can I do ?
And thanks in advance

**Comment by jkmartindale** [comment] 2021-07-15 15:48
Ran into the same issue. The same payload run from regular Windows lacks the 0xACED magic bytes while generating a payload in WSL works as expected:
![image](https://user-images.githubusercontent.com/11380394/125817770-6f86d05e-6779-4a8c-9f46-29c83ee1733a.png)

**Comment by frohoff** [comment] 2021-08-17 22:06
The incorrect magic header seems to be caused by powershell mangling piped binary data.

https://brianreiter.org/2010/01/29/powershells-object-pipeline-corrupts-piped-binary-data/
https://www.leeholmes.com/redirecting-binary-output-in-powershell/

* hex dump directly from powershell execution of ysoserial:
```powershell
> java -jar .\target\ysoserial-0.0.6-SNAPSHOT-all.jar CommonsCollections1 hostname | format-hex | select-object -first 5

           00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F

00000000   3F 3F 00 05 73 72 00 32 73 75 6E 2E 72 65 66 6C  ??..sr.2sun.refl
00000010   65 63 74 2E 61 6E 6E 6F 74 61 74 69 6F 6E 2E 41  ect.annotation.A
```

* hex dump from powershell execution of ysoserial via `test.bin` output file:

```powershell
> java -jar .\target\ysoserial-0.0.6-SNAPSHOT-all.jar CommonsCollections1 hostname | Out-File -Encoding oem test.bin
> get-item .\test.bin | Format-Hex | select-object -first 2

           00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F

00000000   AC ED 00 05 73 72 00 32 73 75 6E 2E 72 65 66 6C  ¬í..sr.2sun.refl
00000010   65 63 74 2E 61 6E 6E 6F 74 61 74 69 6F 6E 2E 41  ect.annotation.A
```

Note that it also works properly when using `cmd` instead of powershell.

Closing for now.

**Closed by frohoff** 2021-08-17 22:06 UTC

**Comment by ProgramFilesx86** [comment] 2021-08-18 09:07
Thank you

**Comment by jkmartindale** [comment] 2021-08-18 15:09
Would you consider adding an output argument to ysoserial? It's not exactly work-stopping to have to drop into cmd or a *nix environment to generate payloads, but it might help lessen the confusion that PowerShell causes.
