### ISSUE TITLE
I am getting below error while using ysoserial

### ISSUE THREAD

**Issue by bhaleraosumit7** [frohoff/ysoserial#179] opened 2022-04-16 06:07 UTC
Error while generating or serializing payload
java.lang.IllegalAccessError: class ysoserial.payloads.util.Gadgets (in unnamed module @0x202e401) cannot access class com.sun.org.apache.xalan.internal.xsltc.trax.TemplatesImpl (in module java.xml) because module java.xml does not export com.sun.org.apache.xalan.internal.xsltc.trax to unnamed module @0x202e401
        at ysoserial.payloads.util.Gadgets.createTemplatesImpl(Gadgets.java:102)
        at ysoserial.payloads.CommonsCollections4.getObject(CommonsCollections4.java:32)
        at ysoserial.payloads.CommonsCollections4.getObject(CommonsCollections4.java:26)
        at ysoserial.GeneratePayload.main(GeneratePayload.java:34)

Anyone know how to solve this

**Comment by WithD-raw** [comment] 2022-04-22 07:24
I meet the same error, do you solved?

**Comment by frohoff** [comment] 2022-04-23 20:15
This is a duplicate of #176.

See https://github.com/frohoff/ysoserial/issues/176#issuecomment-1059848122.

**Closed by frohoff** 2022-04-23 20:15 UTC
Labels: duplicate
